version: '3.7'

services:
    db:
        image: postgres
        volumes:
          - ./data/db:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        container_name: rocket-core-db
    rocket-core-node:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
          - ./src:/home/node/app/src
          - ./nodemon.json:/home/node/app/nodemon.json
        container_name: rocket-core-node
        expose:
          - '8000'
        ports:
          - '8000:8000'
        command: npm run dev
        environment:
          - POSTGRES_NAME=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        depends_on:
          - db
networks:
    default:
